/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InviteRouteRouteImport } from './routes/_invite/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as InviteInviteTokenRouteImport } from './routes/_invite/invite/$token'
import { Route as AppWWorkspaceKeyRouteRouteImport } from './routes/_app/w/$workspaceKey/route'
import { Route as AppWWorkspaceKeyIndexRouteImport } from './routes/_app/w/$workspaceKey/index'
import { Route as AppWWorkspaceKeyMembersRouteImport } from './routes/_app/w/$workspaceKey/members'
import { Route as AppWWorkspaceKeyFilesRouteImport } from './routes/_app/w/$workspaceKey/files'
import { Route as AppWWorkspaceKeyContactsRouteImport } from './routes/_app/w/$workspaceKey/contacts'
import { Route as AppWWorkspaceKeySettingsRouteRouteImport } from './routes/_app/w/$workspaceKey/settings/route'
import { Route as AppWWorkspaceKeySettingsIndexRouteImport } from './routes/_app/w/$workspaceKey/settings/index'
import { Route as AppWWorkspaceKeySettingsWorkspaceRouteImport } from './routes/_app/w/$workspaceKey/settings/workspace'
import { Route as AppWWorkspaceKeySettingsBillingRouteImport } from './routes/_app/w/$workspaceKey/settings/billing'

const InviteRouteRoute = InviteRouteRouteImport.update({
  id: '/_invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const InviteInviteTokenRoute = InviteInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => InviteRouteRoute,
} as any)
const AppWWorkspaceKeyRouteRoute = AppWWorkspaceKeyRouteRouteImport.update({
  id: '/w/$workspaceKey',
  path: '/w/$workspaceKey',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWWorkspaceKeyIndexRoute = AppWWorkspaceKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWWorkspaceKeyRouteRoute,
} as any)
const AppWWorkspaceKeyMembersRoute = AppWWorkspaceKeyMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppWWorkspaceKeyRouteRoute,
} as any)
const AppWWorkspaceKeyFilesRoute = AppWWorkspaceKeyFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppWWorkspaceKeyRouteRoute,
} as any)
const AppWWorkspaceKeyContactsRoute =
  AppWWorkspaceKeyContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AppWWorkspaceKeyRouteRoute,
  } as any)
const AppWWorkspaceKeySettingsRouteRoute =
  AppWWorkspaceKeySettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWWorkspaceKeyRouteRoute,
  } as any)
const AppWWorkspaceKeySettingsIndexRoute =
  AppWWorkspaceKeySettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWWorkspaceKeySettingsRouteRoute,
  } as any)
const AppWWorkspaceKeySettingsWorkspaceRoute =
  AppWWorkspaceKeySettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AppWWorkspaceKeySettingsRouteRoute,
  } as any)
const AppWWorkspaceKeySettingsBillingRoute =
  AppWWorkspaceKeySettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppWWorkspaceKeySettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRoute
  '/callback': typeof AuthCallbackRoute
  '/sign-in': typeof AuthSignInRoute
  '/w/$workspaceKey': typeof AppWWorkspaceKeyRouteRouteWithChildren
  '/invite/$token': typeof InviteInviteTokenRoute
  '/w/$workspaceKey/settings': typeof AppWWorkspaceKeySettingsRouteRouteWithChildren
  '/w/$workspaceKey/contacts': typeof AppWWorkspaceKeyContactsRoute
  '/w/$workspaceKey/files': typeof AppWWorkspaceKeyFilesRoute
  '/w/$workspaceKey/members': typeof AppWWorkspaceKeyMembersRoute
  '/w/$workspaceKey/': typeof AppWWorkspaceKeyIndexRoute
  '/w/$workspaceKey/settings/billing': typeof AppWWorkspaceKeySettingsBillingRoute
  '/w/$workspaceKey/settings/workspace': typeof AppWWorkspaceKeySettingsWorkspaceRoute
  '/w/$workspaceKey/settings/': typeof AppWWorkspaceKeySettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRoute
  '/callback': typeof AuthCallbackRoute
  '/sign-in': typeof AuthSignInRoute
  '/invite/$token': typeof InviteInviteTokenRoute
  '/w/$workspaceKey/contacts': typeof AppWWorkspaceKeyContactsRoute
  '/w/$workspaceKey/files': typeof AppWWorkspaceKeyFilesRoute
  '/w/$workspaceKey/members': typeof AppWWorkspaceKeyMembersRoute
  '/w/$workspaceKey': typeof AppWWorkspaceKeyIndexRoute
  '/w/$workspaceKey/settings/billing': typeof AppWWorkspaceKeySettingsBillingRoute
  '/w/$workspaceKey/settings/workspace': typeof AppWWorkspaceKeySettingsWorkspaceRoute
  '/w/$workspaceKey/settings': typeof AppWWorkspaceKeySettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_invite': typeof InviteRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/w/$workspaceKey': typeof AppWWorkspaceKeyRouteRouteWithChildren
  '/_invite/invite/$token': typeof InviteInviteTokenRoute
  '/_app/w/$workspaceKey/settings': typeof AppWWorkspaceKeySettingsRouteRouteWithChildren
  '/_app/w/$workspaceKey/contacts': typeof AppWWorkspaceKeyContactsRoute
  '/_app/w/$workspaceKey/files': typeof AppWWorkspaceKeyFilesRoute
  '/_app/w/$workspaceKey/members': typeof AppWWorkspaceKeyMembersRoute
  '/_app/w/$workspaceKey/': typeof AppWWorkspaceKeyIndexRoute
  '/_app/w/$workspaceKey/settings/billing': typeof AppWWorkspaceKeySettingsBillingRoute
  '/_app/w/$workspaceKey/settings/workspace': typeof AppWWorkspaceKeySettingsWorkspaceRoute
  '/_app/w/$workspaceKey/settings/': typeof AppWWorkspaceKeySettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/callback'
    | '/sign-in'
    | '/w/$workspaceKey'
    | '/invite/$token'
    | '/w/$workspaceKey/settings'
    | '/w/$workspaceKey/contacts'
    | '/w/$workspaceKey/files'
    | '/w/$workspaceKey/members'
    | '/w/$workspaceKey/'
    | '/w/$workspaceKey/settings/billing'
    | '/w/$workspaceKey/settings/workspace'
    | '/w/$workspaceKey/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/callback'
    | '/sign-in'
    | '/invite/$token'
    | '/w/$workspaceKey/contacts'
    | '/w/$workspaceKey/files'
    | '/w/$workspaceKey/members'
    | '/w/$workspaceKey'
    | '/w/$workspaceKey/settings/billing'
    | '/w/$workspaceKey/settings/workspace'
    | '/w/$workspaceKey/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_invite'
    | '/_app/settings'
    | '/_auth/callback'
    | '/_auth/sign-in'
    | '/_app/'
    | '/_app/w/$workspaceKey'
    | '/_invite/invite/$token'
    | '/_app/w/$workspaceKey/settings'
    | '/_app/w/$workspaceKey/contacts'
    | '/_app/w/$workspaceKey/files'
    | '/_app/w/$workspaceKey/members'
    | '/_app/w/$workspaceKey/'
    | '/_app/w/$workspaceKey/settings/billing'
    | '/_app/w/$workspaceKey/settings/workspace'
    | '/_app/w/$workspaceKey/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InviteRouteRoute: typeof InviteRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_invite': {
      id: '/_invite'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InviteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_invite/invite/$token': {
      id: '/_invite/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteInviteTokenRouteImport
      parentRoute: typeof InviteRouteRoute
    }
    '/_app/w/$workspaceKey': {
      id: '/_app/w/$workspaceKey'
      path: '/w/$workspaceKey'
      fullPath: '/w/$workspaceKey'
      preLoaderRoute: typeof AppWWorkspaceKeyRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/w/$workspaceKey/': {
      id: '/_app/w/$workspaceKey/'
      path: '/'
      fullPath: '/w/$workspaceKey/'
      preLoaderRoute: typeof AppWWorkspaceKeyIndexRouteImport
      parentRoute: typeof AppWWorkspaceKeyRouteRoute
    }
    '/_app/w/$workspaceKey/members': {
      id: '/_app/w/$workspaceKey/members'
      path: '/members'
      fullPath: '/w/$workspaceKey/members'
      preLoaderRoute: typeof AppWWorkspaceKeyMembersRouteImport
      parentRoute: typeof AppWWorkspaceKeyRouteRoute
    }
    '/_app/w/$workspaceKey/files': {
      id: '/_app/w/$workspaceKey/files'
      path: '/files'
      fullPath: '/w/$workspaceKey/files'
      preLoaderRoute: typeof AppWWorkspaceKeyFilesRouteImport
      parentRoute: typeof AppWWorkspaceKeyRouteRoute
    }
    '/_app/w/$workspaceKey/contacts': {
      id: '/_app/w/$workspaceKey/contacts'
      path: '/contacts'
      fullPath: '/w/$workspaceKey/contacts'
      preLoaderRoute: typeof AppWWorkspaceKeyContactsRouteImport
      parentRoute: typeof AppWWorkspaceKeyRouteRoute
    }
    '/_app/w/$workspaceKey/settings': {
      id: '/_app/w/$workspaceKey/settings'
      path: '/settings'
      fullPath: '/w/$workspaceKey/settings'
      preLoaderRoute: typeof AppWWorkspaceKeySettingsRouteRouteImport
      parentRoute: typeof AppWWorkspaceKeyRouteRoute
    }
    '/_app/w/$workspaceKey/settings/': {
      id: '/_app/w/$workspaceKey/settings/'
      path: '/'
      fullPath: '/w/$workspaceKey/settings/'
      preLoaderRoute: typeof AppWWorkspaceKeySettingsIndexRouteImport
      parentRoute: typeof AppWWorkspaceKeySettingsRouteRoute
    }
    '/_app/w/$workspaceKey/settings/workspace': {
      id: '/_app/w/$workspaceKey/settings/workspace'
      path: '/workspace'
      fullPath: '/w/$workspaceKey/settings/workspace'
      preLoaderRoute: typeof AppWWorkspaceKeySettingsWorkspaceRouteImport
      parentRoute: typeof AppWWorkspaceKeySettingsRouteRoute
    }
    '/_app/w/$workspaceKey/settings/billing': {
      id: '/_app/w/$workspaceKey/settings/billing'
      path: '/billing'
      fullPath: '/w/$workspaceKey/settings/billing'
      preLoaderRoute: typeof AppWWorkspaceKeySettingsBillingRouteImport
      parentRoute: typeof AppWWorkspaceKeySettingsRouteRoute
    }
  }
}

interface AppWWorkspaceKeySettingsRouteRouteChildren {
  AppWWorkspaceKeySettingsBillingRoute: typeof AppWWorkspaceKeySettingsBillingRoute
  AppWWorkspaceKeySettingsWorkspaceRoute: typeof AppWWorkspaceKeySettingsWorkspaceRoute
  AppWWorkspaceKeySettingsIndexRoute: typeof AppWWorkspaceKeySettingsIndexRoute
}

const AppWWorkspaceKeySettingsRouteRouteChildren: AppWWorkspaceKeySettingsRouteRouteChildren =
  {
    AppWWorkspaceKeySettingsBillingRoute: AppWWorkspaceKeySettingsBillingRoute,
    AppWWorkspaceKeySettingsWorkspaceRoute:
      AppWWorkspaceKeySettingsWorkspaceRoute,
    AppWWorkspaceKeySettingsIndexRoute: AppWWorkspaceKeySettingsIndexRoute,
  }

const AppWWorkspaceKeySettingsRouteRouteWithChildren =
  AppWWorkspaceKeySettingsRouteRoute._addFileChildren(
    AppWWorkspaceKeySettingsRouteRouteChildren,
  )

interface AppWWorkspaceKeyRouteRouteChildren {
  AppWWorkspaceKeySettingsRouteRoute: typeof AppWWorkspaceKeySettingsRouteRouteWithChildren
  AppWWorkspaceKeyContactsRoute: typeof AppWWorkspaceKeyContactsRoute
  AppWWorkspaceKeyFilesRoute: typeof AppWWorkspaceKeyFilesRoute
  AppWWorkspaceKeyMembersRoute: typeof AppWWorkspaceKeyMembersRoute
  AppWWorkspaceKeyIndexRoute: typeof AppWWorkspaceKeyIndexRoute
}

const AppWWorkspaceKeyRouteRouteChildren: AppWWorkspaceKeyRouteRouteChildren = {
  AppWWorkspaceKeySettingsRouteRoute:
    AppWWorkspaceKeySettingsRouteRouteWithChildren,
  AppWWorkspaceKeyContactsRoute: AppWWorkspaceKeyContactsRoute,
  AppWWorkspaceKeyFilesRoute: AppWWorkspaceKeyFilesRoute,
  AppWWorkspaceKeyMembersRoute: AppWWorkspaceKeyMembersRoute,
  AppWWorkspaceKeyIndexRoute: AppWWorkspaceKeyIndexRoute,
}

const AppWWorkspaceKeyRouteRouteWithChildren =
  AppWWorkspaceKeyRouteRoute._addFileChildren(
    AppWWorkspaceKeyRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWWorkspaceKeyRouteRoute: typeof AppWWorkspaceKeyRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppWWorkspaceKeyRouteRoute: AppWWorkspaceKeyRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface InviteRouteRouteChildren {
  InviteInviteTokenRoute: typeof InviteInviteTokenRoute
}

const InviteRouteRouteChildren: InviteRouteRouteChildren = {
  InviteInviteTokenRoute: InviteInviteTokenRoute,
}

const InviteRouteRouteWithChildren = InviteRouteRoute._addFileChildren(
  InviteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InviteRouteRoute: InviteRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
